#' cgNetwork
#'
#' This function allows the user to find neighbor genes network of mutation status of interested gene.
#' It returns two igraph lists.
#' @param countdata RNAseq countdata.
#' @param mut_df Mutation status.
#' @param common_neighbor Neighbor genes of interesting gene generated by neighbor_finder().
#' @param cor_method correlation coeffiecint method "spearman" or "pearson". Defaults to "spearman"
#' @param weight.cut.off cut off value of network weight to reduce edges. Defaults to .5
#' @examples
#' cgNetwork_list <- cgNetwork(countdata, mut_df, common_neighbor, cor_method = "spearman", weight.cut.off=.5)
#' @export

cgNetwork <- function(countdata, mut_df, common_neighbor, cor_method = "spearman", weight.cut.off=.5){
  wt <- rownames(mut_df)[which(mut_df[,1]==0)]
  mut <- rownames(mut_df)[which(mut_df[,1]==1)]

  na_omit_df <- na.omit(countdata)
  rnaseq <- data.frame(t(na_omit_df))

  rnaseq_wt <- rnaseq[wt,common_neighbor]
  rnaseq_mut <- rnaseq[mut,common_neighbor]

  rnaseq_wt <- rnaseq_wt[, !sapply(rnaseq_wt, function(x) { sd(x) == 0} )]
  rnaseq_mut <- rnaseq_mut[, !sapply(rnaseq_mut, function(x) { sd(x) == 0} )]

  rm(na_omit_df, wt, mut, rnaseq)

  rnaseq_cor_wt <- cor(rnaseq_wt, method = cor_method)
  rnaseq_cor_mut <- cor(rnaseq_mut, method = cor_method)
  rm(rnaseq_wt, rnaseq_mut)
  cor_wt <- rnaseq_cor_wt
  cor_mut <- rnaseq_cor_mut

  g1 <-  igraph::graph.adjacency(cor_wt, weighted=TRUE, mode="lower")
  g1 <- igraph::delete.edges(g1, igraph::E(g1)[ weight < weight.cut.off ])
  g1 <- igraph::simplify(g1, remove.multiple = TRUE, remove.loops = TRUE)
  g1 <- igraph::delete.vertices(g1, which(igraph::degree(g1)<1))

  g2 <-  igraph::graph.adjacency(cor_mut, weighted=TRUE, mode="lower")
  g2 <- igraph::delete.edges(g2, igraph::E(g2)[ weight < weight.cut.off ])
  g2 <- igraph::simplify(g2, remove.multiple = TRUE, remove.loops = TRUE)
  g2 <- igraph::delete.vertices(g2, which(igraph::degree(g2)<1))

  network <- list(g1,g2)
  return(network)
}
