#' DiNetplot
#'
#' Imports:
#' shiny,
#' igraph,
#' dplyr,
#' visNetwork
#'
#' Displays an interactive network plot.
#' @param TCGANetwork_list list of igraph objects, generated by TCGANetwork().
#' @param interest_gene string, gene of interest same as used in the neighbor_finder function.
#' @param mut_gene string, gene by which patients should be separated. There will be one network for WT and one for mutated.
#' @examples
#' DiNetplot(TCGANetwork_list)
#' @export

DiNetplot <- function(TCGANetwork_list){
 library(dplyr)
  ui <- shiny::fluidPage(
    shiny::fluidRow(
      shiny::column(6,
                    visNetwork::visNetworkOutput('vis1')),
      shiny::column(6,
                    visNetwork::visNetworkOutput('vis2'))
    )
  )

  server <- function(input, output) {

    g1 <- TCGANetwork_list[[1]]
    nodes1 <- data.frame(igraph::V(g1)$name, label=NA)
    colnames(nodes1) <- c("id", "label")
    nodes1$label <- nodes1$id

    g2 <- TCGANetwork_list[[2]]
    nodes2 <- data.frame(igraph::V(g2)$name, label=NA)
    colnames(nodes2) <- c("id", "label")
    nodes2$label <- nodes2$id

    #Edges
    edges1 <- igraph::get.data.frame(g1)
    colnames(edges1) <- c("from", "to", "width")

    edges2 <- igraph::get.data.frame(g2)
    colnames(edges2) <- c("from", "to", "width")

    #Clustering
    cluster1 <- igraph::cluster_louvain(g1)
    cluster_df1 <- data.frame(as.list(igraph::membership(cluster1)))
    cluster_df1 <- as.data.frame(t(cluster_df1))
    cluster_df1$label <- rownames(cluster_df1)

    cluster2 <- igraph::cluster_louvain(g2)
    cluster_df2 <- data.frame(as.list(igraph::membership(cluster2)))
    cluster_df2 <- as.data.frame(t(cluster_df2))
    cluster_df2$label <- rownames(cluster_df2)

    #Create group column
    nodes1 <- dplyr::left_join(nodes1, cluster_df1, by = "label")
    colnames(nodes1)[3] <- "group"

    nodes2 <- dplyr::left_join(nodes2, cluster_df2, by = "label")
    colnames(nodes2)[3] <- "group"

    output$vis1 <- visNetwork::renderVisNetwork(
      {
        visNetwork::visNetwork(nodes1, edges1, main = paste("Network in wild type"), width = "100%") %>%
          visNetwork::visIgraphLayout() %>%
          visNetwork::visNodes(
            shape = "dot",
            color = list(
              background = "#0085AF",
              border = "#013848",
              highlight = "#FF8000"
            ),
            shadow = list(enabled = TRUE, size = 10)
          ) %>%
          visNetwork::visEdges(
            shadow = FALSE,
            color = list(color = "#0085AF", highlight = "#C62F4B")
          ) %>%
          visNetwork::visOptions(highlightNearest = list(enabled = T, degree = 1, hover = T),
                                 selectedBy = "group") %>%
          visNetwork::visLayout(randomSeed = 11) %>%
          return
      })
    output$vis2 <- visNetwork::renderVisNetwork(
      {
        visNetwork::visNetwork(nodes2, edges2, main = paste("Network in mutation"), width = "100%") %>%
          visNetwork::visIgraphLayout() %>%
          visNetwork::visNodes(
            shape = "dot",
            color = list(
              background = "#0085AF",
              border = "#013848",
              highlight = "#FF8000"
            ),
            shadow = list(enabled = TRUE, size = 10)
          ) %>%
          visNetwork::visEdges(
            shadow = FALSE,
            color = list(color = "#0085AF", highlight = "#C62F4B")
          ) %>%
          visNetwork::visOptions(highlightNearest = list(enabled = T, degree = 1, hover = T),
                                 selectedBy = "group") %>%
          visNetwork::visLayout(randomSeed = 11) %>%
          return
      })
  }

  return(shiny::shinyApp(ui = ui, server = server))

}
DiNetplot(TCGANetwork_list)
