#' neighbor_finder
#'
#' This function allows the user to find neighbor genes network of interested gene.
#' @param countdata TCGA RNAseq countdata generated by TCGA_RNAseq_RSEM().
#' @param gene Interesting gene to find network. Defaults to "CDKN1A".
#' @param cor_method correlation coeffiecint method "spearman" or "pearson". Defaults to "spearman"
#' @param cor.cut.off cut off value of correlation coeffiecint to build network. Defaults to .39
#' @param weight.cut.off cut off value of network weight to reduce edges. Defaults to .5
#' @examples
#' common_neighbor <- neighbor_finder(countdata, gene="CDKN1A", cor_method = "spearman", cor.cut.off=.39, weight.cut.off=.5)
#' @export

neighbor_finder <- function(countdata, gene="CDKN1A", cor_method = "spearman", cor.cut.off=.39, weight.cut.off=.5){
  na_omit_df <- na.omit(countdata)
  rnaseq <- data.frame(t(na_omit_df))
  rnaseq <- rnaseq[, !sapply(rnaseq, function(x) { sd(x) == 0} )]
  cor_df <- cor(rnaseq, method = cor_method)
  rm(na_omit_df, rnaseq)
  cor_df[cor_df == 1] <- 0
  cor_df[cor_df < cor.cut.off] <- 0
  net <- igraph::graph_from_adjacency_matrix(cor_df, mode='undirected', weighted = T, diag=F)
  net <- igraph::simplify(net, remove.multiple = T, remove.loops = T)
  net.sp <- igraph::delete_edges(net, igraph::E(net)[weight<weight.cut.off])
  neigh.nodes <- igraph::neighbors(net.sp, igraph::V(net.sp)[gene])
  common_neig <- c(names(neigh.nodes),gene)
  return(common_neig)
}
